# Generated by scripts/publish-tap-formulae.sh in johnhkchen/lisa. Do not edit by hand:
# the next release regenerates this file and your edit disappears.
# Channel: nightly.
class LisaNightly < Formula
  desc "CLI for Lisa DAG-driven concurrent task scheduling (nightly channel)"
  homepage "https://github.com/johnhkchen/lisa"
  version "0.5.0"
  if OS.mac?
    if Hardware::CPU.arm?
      url "https://github.com/johnhkchen/lisa/releases/download/v0.5.0/lisa-cli-aarch64-apple-darwin.tar.gz"
      sha256 "c8543d0d9305a8bf72016894f8c2c8c82564fd974f0cd68aba40d3206ae4d7ec"
    end
    if Hardware::CPU.intel?
      url "https://github.com/johnhkchen/lisa/releases/download/v0.5.0/lisa-cli-x86_64-apple-darwin.tar.gz"
      sha256 "1b25ab342f3d36089d5b8708971cf4e82c177442cb05d15df18633cd460e6fe6"
    end
  end
  if OS.linux?
    if Hardware::CPU.arm?
      url "https://github.com/johnhkchen/lisa/releases/download/v0.5.0/lisa-cli-aarch64-unknown-linux-musl.tar.gz"
      sha256 "d3b8a03b1b371113e0c03a8e671f4d01f536376bb401e0529741f7bd5ad5b4bc"
    end
    if Hardware::CPU.intel?
      url "https://github.com/johnhkchen/lisa/releases/download/v0.5.0/lisa-cli-x86_64-unknown-linux-musl.tar.gz"
      sha256 "1078c735be4d8b169d71d7cba36d77941acbf3b7588008a56d12726aa1387593"
    end
  end
  license "MIT"
  conflicts_with "lisa", "lisa-canary", because: "they install lisa from different release channels"

  BINARY_ALIASES = {
    "aarch64-apple-darwin":               {},
    "aarch64-unknown-linux-gnu":          {},
    "aarch64-unknown-linux-musl-dynamic": {},
    "aarch64-unknown-linux-musl-static":  {},
    "x86_64-apple-darwin":                {},
    "x86_64-unknown-linux-gnu":           {},
    "x86_64-unknown-linux-musl-dynamic":  {},
    "x86_64-unknown-linux-musl-static":   {},
  }.freeze

  def target_triple
    cpu = Hardware::CPU.arm? ? "aarch64" : "x86_64"
    os = OS.mac? ? "apple-darwin" : "unknown-linux-gnu"

    "#{cpu}-#{os}"
  end

  def install_binary_aliases!
    BINARY_ALIASES[target_triple.to_sym].each do |source, dests|
      dests.each do |dest|
        bin.install_symlink bin/source.to_s => dest
      end
    end
  end

  def install
    if OS.mac? && Hardware::CPU.arm?
      bin.install "lisa"
    end
    if OS.mac? && Hardware::CPU.intel?
      bin.install "lisa"
    end
    if OS.linux? && Hardware::CPU.arm?
      bin.install "lisa"
    end
    if OS.linux? && Hardware::CPU.intel?
      bin.install "lisa"
    end

    install_binary_aliases!

    # Homebrew will automatically install these, so we don't need to do that
    doc_files = Dir["README.*", "readme.*", "LICENSE", "LICENSE.*", "CHANGELOG.*"]
    leftover_contents = Dir["*"] - doc_files

    # Install any leftover files in pkgshare; these are probably config or
    # sample files.
    pkgshare.install(*leftover_contents) unless leftover_contents.empty?
  end
end
