# Generated by scripts/publish-tap-formulae.sh in johnhkchen/lisa. Do not edit by hand:
# the next release regenerates this file and your edit disappears.
# Channel: nightly.
class LisaNightly < Formula
  desc "CLI for Lisa DAG-driven concurrent task scheduling (nightly channel)"
  homepage "https://github.com/johnhkchen/lisa"
  version "0.4.4"
  if OS.mac?
    if Hardware::CPU.arm?
      url "https://github.com/johnhkchen/lisa/releases/download/v0.4.4/lisa-cli-aarch64-apple-darwin.tar.gz"
      sha256 "ede88a06aa63d2003e6e4f1fbd99febbf6e44d21d930f2a7ec888baf582996d0"
    end
    if Hardware::CPU.intel?
      url "https://github.com/johnhkchen/lisa/releases/download/v0.4.4/lisa-cli-x86_64-apple-darwin.tar.gz"
      sha256 "542e7984156c3370dacf642cd3d6c8efb969075fce3814e5d33a2d014b70ce93"
    end
  end
  if OS.linux?
    if Hardware::CPU.arm?
      url "https://github.com/johnhkchen/lisa/releases/download/v0.4.4/lisa-cli-aarch64-unknown-linux-musl.tar.gz"
      sha256 "c4093d05d17be57ed63ce08ff85e2eb412094125fb43f01c2b1d9dfaade48115"
    end
    if Hardware::CPU.intel?
      url "https://github.com/johnhkchen/lisa/releases/download/v0.4.4/lisa-cli-x86_64-unknown-linux-musl.tar.gz"
      sha256 "77d514542efce002f0400faff0f306e30103d84176fffd2cdbdfca287db964ab"
    end
  end
  license "MIT"
  conflicts_with "lisa", "lisa-canary", because: "they install lisa from different release channels"

  BINARY_ALIASES = {
    "aarch64-apple-darwin":               {},
    "aarch64-unknown-linux-gnu":          {},
    "aarch64-unknown-linux-musl-dynamic": {},
    "aarch64-unknown-linux-musl-static":  {},
    "x86_64-apple-darwin":                {},
    "x86_64-unknown-linux-gnu":           {},
    "x86_64-unknown-linux-musl-dynamic":  {},
    "x86_64-unknown-linux-musl-static":   {},
  }.freeze

  def target_triple
    cpu = Hardware::CPU.arm? ? "aarch64" : "x86_64"
    os = OS.mac? ? "apple-darwin" : "unknown-linux-gnu"

    "#{cpu}-#{os}"
  end

  def install_binary_aliases!
    BINARY_ALIASES[target_triple.to_sym].each do |source, dests|
      dests.each do |dest|
        bin.install_symlink bin/source.to_s => dest
      end
    end
  end

  def install
    if OS.mac? && Hardware::CPU.arm?
      bin.install "lisa"
    end
    if OS.mac? && Hardware::CPU.intel?
      bin.install "lisa"
    end
    if OS.linux? && Hardware::CPU.arm?
      bin.install "lisa"
    end
    if OS.linux? && Hardware::CPU.intel?
      bin.install "lisa"
    end

    install_binary_aliases!

    # Homebrew will automatically install these, so we don't need to do that
    doc_files = Dir["README.*", "readme.*", "LICENSE", "LICENSE.*", "CHANGELOG.*"]
    leftover_contents = Dir["*"] - doc_files

    # Install any leftover files in pkgshare; these are probably config or
    # sample files.
    pkgshare.install(*leftover_contents) unless leftover_contents.empty?
  end
end
