# Generated by scripts/publish-tap-formulae.sh in johnhkchen/lisa. Do not edit by hand:
# the next release regenerates this file and your edit disappears.
# Channel: canary.
class LisaCanary < Formula
  desc "CLI for Lisa DAG-driven concurrent task scheduling (canary channel)"
  homepage "https://github.com/johnhkchen/lisa"
  version "0.5.0-rc.3"
  if OS.mac?
    if Hardware::CPU.arm?
      url "https://github.com/johnhkchen/lisa/releases/download/v0.5.0-rc.3/lisa-cli-aarch64-apple-darwin.tar.gz"
      sha256 "f2e4b24024bfa273705701e83ee7f6f22b5ef989fadcbb6fee0f16ea57cebcdc"
    end
    if Hardware::CPU.intel?
      url "https://github.com/johnhkchen/lisa/releases/download/v0.5.0-rc.3/lisa-cli-x86_64-apple-darwin.tar.gz"
      sha256 "5b3c3f86602fbeafd6497745e97f64990e4e34bc9d3b09ef595f1b90f299c222"
    end
  end
  if OS.linux?
    if Hardware::CPU.arm?
      url "https://github.com/johnhkchen/lisa/releases/download/v0.5.0-rc.3/lisa-cli-aarch64-unknown-linux-musl.tar.gz"
      sha256 "a31ac3343cd3f2a44e1b7347ec636f688174ccd900af40ed445731ebc8c8a794"
    end
    if Hardware::CPU.intel?
      url "https://github.com/johnhkchen/lisa/releases/download/v0.5.0-rc.3/lisa-cli-x86_64-unknown-linux-musl.tar.gz"
      sha256 "9dcc0fd846d349889dafb24f6120b9ee466d3841668dc17b43027586d6faa009"
    end
  end
  license "MIT"
  conflicts_with "lisa", "lisa-nightly", because: "they install lisa from different release channels"

  BINARY_ALIASES = {
    "aarch64-apple-darwin":               {},
    "aarch64-unknown-linux-gnu":          {},
    "aarch64-unknown-linux-musl-dynamic": {},
    "aarch64-unknown-linux-musl-static":  {},
    "x86_64-apple-darwin":                {},
    "x86_64-unknown-linux-gnu":           {},
    "x86_64-unknown-linux-musl-dynamic":  {},
    "x86_64-unknown-linux-musl-static":   {},
  }.freeze

  def target_triple
    cpu = Hardware::CPU.arm? ? "aarch64" : "x86_64"
    os = OS.mac? ? "apple-darwin" : "unknown-linux-gnu"

    "#{cpu}-#{os}"
  end

  def install_binary_aliases!
    BINARY_ALIASES[target_triple.to_sym].each do |source, dests|
      dests.each do |dest|
        bin.install_symlink bin/source.to_s => dest
      end
    end
  end

  def install
    if OS.mac? && Hardware::CPU.arm?
      bin.install "lisa"
    end
    if OS.mac? && Hardware::CPU.intel?
      bin.install "lisa"
    end
    if OS.linux? && Hardware::CPU.arm?
      bin.install "lisa"
    end
    if OS.linux? && Hardware::CPU.intel?
      bin.install "lisa"
    end

    install_binary_aliases!

    # Homebrew will automatically install these, so we don't need to do that
    doc_files = Dir["README.*", "readme.*", "LICENSE", "LICENSE.*", "CHANGELOG.*"]
    leftover_contents = Dir["*"] - doc_files

    # Install any leftover files in pkgshare; these are probably config or
    # sample files.
    pkgshare.install(*leftover_contents) unless leftover_contents.empty?
  end
end
