# Generated by scripts/publish-tap-formulae.sh in johnhkchen/lisa. Do not edit by hand:
# the next release regenerates this file and your edit disappears.
# Channel: nightly.
class LisaNightly < Formula
  desc "CLI for Lisa DAG-driven concurrent task scheduling (nightly channel)"
  homepage "https://github.com/johnhkchen/lisa"
  version "0.5.1-rc.2"
  if OS.mac?
    if Hardware::CPU.arm?
      url "https://github.com/johnhkchen/lisa/releases/download/v0.5.1-rc.2/lisa-cli-aarch64-apple-darwin.tar.gz"
      sha256 "2b9d28689d1006b04ea35f3ff11f13f8858ebb28d9c2fbcc3135b0786e38fccd"
    end
    if Hardware::CPU.intel?
      url "https://github.com/johnhkchen/lisa/releases/download/v0.5.1-rc.2/lisa-cli-x86_64-apple-darwin.tar.gz"
      sha256 "7a5298cd4010714e50793425d11f158452bcb0d19ba4155ac1ae24792aeed330"
    end
  end
  if OS.linux?
    if Hardware::CPU.arm?
      url "https://github.com/johnhkchen/lisa/releases/download/v0.5.1-rc.2/lisa-cli-aarch64-unknown-linux-musl.tar.gz"
      sha256 "87d67027fadd413c4ee6d76dadc31bfc41362c16b6244d889bcfb4c7eb4dab34"
    end
    if Hardware::CPU.intel?
      url "https://github.com/johnhkchen/lisa/releases/download/v0.5.1-rc.2/lisa-cli-x86_64-unknown-linux-musl.tar.gz"
      sha256 "a28acf50cfb9352cf497c71db17240e5dfe146815ec691430496633344692752"
    end
  end
  license "MIT"
  conflicts_with "lisa", "lisa-canary", because: "they install lisa from different release channels"

  BINARY_ALIASES = {
    "aarch64-apple-darwin":               {},
    "aarch64-unknown-linux-gnu":          {},
    "aarch64-unknown-linux-musl-dynamic": {},
    "aarch64-unknown-linux-musl-static":  {},
    "x86_64-apple-darwin":                {},
    "x86_64-unknown-linux-gnu":           {},
    "x86_64-unknown-linux-musl-dynamic":  {},
    "x86_64-unknown-linux-musl-static":   {},
  }.freeze

  def target_triple
    cpu = Hardware::CPU.arm? ? "aarch64" : "x86_64"
    os = OS.mac? ? "apple-darwin" : "unknown-linux-gnu"

    "#{cpu}-#{os}"
  end

  def install_binary_aliases!
    BINARY_ALIASES[target_triple.to_sym].each do |source, dests|
      dests.each do |dest|
        bin.install_symlink bin/source.to_s => dest
      end
    end
  end

  def install
    if OS.mac? && Hardware::CPU.arm?
      bin.install "lisa"
    end
    if OS.mac? && Hardware::CPU.intel?
      bin.install "lisa"
    end
    if OS.linux? && Hardware::CPU.arm?
      bin.install "lisa"
    end
    if OS.linux? && Hardware::CPU.intel?
      bin.install "lisa"
    end

    install_binary_aliases!

    # Homebrew will automatically install these, so we don't need to do that
    doc_files = Dir["README.*", "readme.*", "LICENSE", "LICENSE.*", "CHANGELOG.*"]
    leftover_contents = Dir["*"] - doc_files

    # Install any leftover files in pkgshare; these are probably config or
    # sample files.
    pkgshare.install(*leftover_contents) unless leftover_contents.empty?
  end
end
